type 'a t = 'a list
let empty = []
let add x c = x :: c
let map f c = List.map f c
let filter p c = List.filter p c
let partition p c = List.partition p c
let union c1 c2 = List.rev_append c1 c2
let bind f c = List.concat (List.map f c)
let of_list c = c
let to_list c = c
let size = List.length
